export type BaseCARecord = {
  /**
   * CA Organization name as it appears in the CA’s CP, CPS, CP/CPS and audit statements.
   */
  "CA Owner": string;

  /**
   * An internal unique ID for this certificate in the CCADB. This value is assigned by the CCADB.
   */
  "Salesforce Record ID": string;

  /**
   * Defaults to certificate subject CN but can be edited by CA Owners for their intermediate certificate records.
   */
  "Certificate Name": string;

  /**
   * An internal unique ID for the Parent Certificate Name record in Salesforce, assigned by Salesforce.
   */
  "Parent Salesforce Record ID": string;

  /**
   * For intermediate certificates, Parent Certificate Name must be the certificate's Issuer Common Name or Issuer Organization.
   */
  "Parent Certificate Name": string;

  /**
   * One of two values determined when certificate is added to the CCADB:
   *  - Intermediate Certificate
   *  - Root Certificate
   */
  "Certificate Record Type": "Intermediate Certificate" | "Root Certificate";

  /**
   * This is the subordinate CA Owner's name as it appears in the provided audit statements.
   * CA Owners MUST NOT leave this field blank unless both control of the private key and domain/IP control validation
   * activities are performed by the organization listed in the audit statement of the parent certificate.
   */
  "Subordinate CA Owner": string;

  /**
   * Root Store inclusion status for the root certificate that this intermediate certificate chains up to in the CCADB. (Updated via hourly batch process)
   *
   * Example: "Apple: Removed; Google Chrome: Not Included; Microsoft: Disabled; Mozilla: Not Yet Included"
   */
  "Status of Root Cert": string;

  /**
   * A SHA-256 hash of the certificate generated by the CCADB when adding a certificate PEM. */
  "SHA-256 Fingerprint": string;

  /**
   * The notBefore value extracted from the certificate PEM.
   * Format: YYYY.MM.DD */
  "Valid From (GMT)": string;

  /**
   * The notAfter value extracted from the certificate PEM.
   * Format: YYYY.MM.DD */
  "Valid To (GMT)": string;

  /**
   * The authorityKeyIdentifier value extracted from the certificate PEM.
   * Format: base64 */
  "Authority Key Identifier": string;

  /**
   * The subjectKeyIdentifier value extracted from the certificate PEM.
   * Format: base64
   */
  "Subject Key Identifier": string;

  /**
   * A boolean value configured by the CCADB when the certificate PEM was added.
   * - Set to FALSE if the certificate does not contain an Extended Key Usage (EKU) extension.
   * - Set to TRUE if the EKU does not contain id‐kp‐serverAuth or anyExtendedKeyUsage.
   * - If the EKU contains id‐kp‐serverAuth, then set to TRUE if the certificate includes the Name Constraints X.509v3 extension with constraints on dNSName, iPAddress and DirectoryName. Otherwise set to FALSE.
   */
  "Technically Constrained": "true" | "false";

  /**
   * The URLs to the full CRL for certificates issued by this CA, as configured by the CA Owner.
   *
   * Format: JSON array of strings */
  "JSON Array of All Full CRL URLs": string;

  /**
   * When there is no full CRL for certificates issued by this CA, the CA Owner can provide a JSON array whose elements are URLs of partitioned, DER-encoded CRLs that when combined are the equivalent of a full CRL for certificates issued by this CA. The JSON array may omit obsolete partitioned CRLs whose scopes only include expired certificates.
   *
   * Format: JSON array of strings*/
  "JSON Array of Partitioned CRLs": string;

  "DV ACME Directory URL(s)": string;
  "OV ACME Directory URL(s)": string;
  "EV ACME Directory URL(s)": string;
  "IV ACME Directory URL(s)": string;

  /**
   * A picklist value for the name of the Audit Firm that issued the audit statements, as selected by the CA Owner. */
  "Audit Firm": string;
  "Audit Firm Location": string;

  /**
   * A boolean value configured by the CA Owner for intermediate certificates:
   * - Set to TRUE if the current or next audit of the parent certificate includes this certificate. Otherwise set to FALSE, and all applicable audit fields must have values provided by the CA Owner.
   */
  "Audits Same as Parent": "true" | "false";

  /**
   * The URL of the public attestation of conformance to the stated certificate verification requirements by the Qualified Auditor, as configured by the CA Owner. */
  "Standard Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either.  */
  "Standard Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   *
   * Format: YYYY.MM.DD
   **/
  "Standard Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "Standard Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "Standard Audit Period End Date": string;

  /**
   * The URL of the public attestation of conformance to the stated certificate verification requirements (i.e., CA/Browser Forum “Network and Certificate System Security Requirements”) by the Qualified Auditor, as configured by the CA Owner. */
  "NetSec Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either. */
  "NetSec Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   *
   * Format: YYYY.MM.DD
   */
  "NetSec Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "NetSec Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "NetSec Audit Period End Date": string;

  /**
   *
   * The URL of the public attestation of conformance to the stated certificate verification requirements (CA/Browser Forum “Baseline Requirements for the Issuance and Management of Publicly-Trusted TLS Server Certificates”) by the Qualified Auditor, as configured by the CA Owner.
   */
  "TLS BR Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either.
   */
  "TLS BR Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   *
   * Format: YYYY.MM.DD
   */
  "TLS BR Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "TLS BR Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "TLS BR Audit Period End Date": string;

  /**
   * The URL of the public attestation of conformance to the stated certificate verification requirements (CA/Browser Forum “Guidelines for the Issuance and Management of Extended Validation Certificates”) by the Qualified Auditor, as configured by the CA Owner.
   */
  "TLS EVG Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either.
   */
  "TLS EVG Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   */
  "TLS EVG Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   */
  "TLS EVG Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   */
  "TLS EVG Audit Period End Date": string;

  /**
   * The URL of the public attestation of conformance to the stated certificate verification requirements (CA/Browser Forum “Baseline Requirements for the Issuance and Management of Publicly-Trusted CodeSigning Certificates”) by the Qualified Auditor, as configured by the CA Owner.
   */
  "Code Signing Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either.
   */
  "Code Signing Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   *
   * Format: YYYY.MM.DD
   */
  "Code Signing Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "Code Signing Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "Code Signing Audit Period End Date": string;

  /**
   * The URL of the public attestation of conformance to the stated certificate verification requirements (CA/Browser Forum “Baseline Requirements for the Issuance and Management of Publicly-Trusted S/MIME Certificates”) by the Qualified Auditor, as configured by the CA Owner.
   */
  "S/MIME BR Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either.
   */
  "S/MIME BR Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   *
   * Format: YYYY.MM.DD
   */
  "S/MIME BR Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "S/MIME BR Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "S/MIME BR Audit Period End Date": string;

  /**
   * The URL of the public attestation of conformance to the stated certificate verification requirements (Mark Certificate Requirements) by the Qualified Auditor, as configured by the CA Owner.
   */
  "VMC Audit URL": string;

  /**
   * A picklist value for the type of audit scheme used, as selected by the CA Owner. In most cases this is either WebTrust or ETSI EN 319 411. In some cases this is an equivalent of either.
   */
  "VMC Audit Type": string;

  /**
   * The date the audit statement was issued by the Qualified Auditor, as configured by the CA Owner.
   *
   * Format: YYYY.MM.DD
   */
  "VMC Audit Statement Date": string;

  /**
   * The start date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "VMC Audit Period Start Date": string;

  /**
   * The end date for the period of time of CA operations examined by the Qualified Auditor.
   *
   * Format: YYYY.MM.DD
   */
  "VMC Audit Period End Date": string;

  /**
   * Notes about the documentation, such as which language the documents are in, or additional documents that need to be listed, as configured by the CA Owner.
   */
  "Policy Documentation": string;

  /**
   * The URL to the document repository pertaining to this certificate, as configured by the CA Owner.
   */
  "CA Document Repository": string;

  /**
   * The URL to CP documentation specific to this certificate, as configured by the CA Owner.
   * This value must be populated if ‘CP Same as Parent’ is set to FALSE.
   */
  "Certificate Policy (CP) URL": string;

  /**
   * The date the CP documentation specific to this certificate became effective, as configured by the CA Owner.
   * This value must be populated if ‘CP Same as Parent’ is set to FALSE.
   *
   * Format: YYYY.MM.DD
   */
  "CP Effective Date": string;

  /**
   * The URL to CPS documentation specific to this certificate, as configured by the CA Owner.
   * This value must be populated if ‘CPS Same as Parent’ is set to FALSE.
   */
  "Certificate Practice Statement (CPS) URL": string;

  /**
   * The date the CPS documentation specific to this certificate became effective, as configured by the CA Owner.
   * This value must be populated if ‘CPS Same as Parent’ is set to FALSE.
   *
   * Format: YYYY.MM.DD
   */
  "CPS Effective Date": string;

  /**
   * The URL to the combined CP/CPS documentation specific to this certificate, as configured by the CA Owner.
   * This value must be populated if ‘CP/CPS Same as Parent’ is set to FALSE.
   */
  "Certificate Practice & Policy Statement": "";

  /**
   * The date the combined CP/CPS documentation specific to this certificate became effective, as configured by the CA Owner. This value must be populated if ‘CP/CPS Same as Parent’ is set to FALSE.
   *
   * Format: YYYY.MM.DD
   */
  "CP/CPS Effective Date": string;
  /**
   * The URL to the combined Markdown or AsciiDoc CP/CPS documentation specific to this certificate, as configured by the CA Owner. This value must be populated if ‘MD/AsciiDoc CP/CPS Same as Parent’ is set to FALSE.
   */
  "MD/AsciiDoc CP/CPS URL": string;
  /**
   * The date the combined Markdown or AsciiDoc CP/CPS documentation specific to this certificate became effective, as configured by the CA Owner. This value must be populated if ‘MD/AsciiDoc CP/CPS Same as Parent’ is set to FALSE.
   */
  "MD/AsciiDoc CP/CPS Effective Date": string;
  /**
   * The URL to a website with a valid TLS certificate that chains up to the root certificate, as configured by the CA Owner.
   */
  "Test Website URL - Valid": string;
  /**
   * The URL to a website with an expired TLS certificate that chains up to the root certificate, as configured by the CA Owner.
   */
  "Test Website URL - Expired": string;
  /**
   * The URL to a website with a revoked TLS certificate that chains up to the root certificate, as configured by the CA Owner.
   */
  "Test Website URL - Revoked": string;
  /**
   * A boolean value configured by the CCADB:
   * - Set to TRUE for a root certificate record if 'Trust Bits For All Root Stores' contains Server Authentication.
   * - Set to TRUE for an intermediate certificate record if 'Derived Trust Bits' contains Server Authentication.
   * - Otherwise set to FALSE.
   */
  "TLS Capable": "True" | "False";
  /**
   * A boolean value configured by the CCADB:
   * - Set to TRUE for a root certificate record if ‘Apple EV Enabled’ is set to TRUE, or ‘ExtendedValidation.cpp OIDs is not null, or ‘Microsoft EV_SSL_Enabled is set to TRUE, or ‘Google Chrome EV Enabled’ is set to TRUE.
   * - Set to TRUE for an intermediate certificate record if 'EV SSL Capable’' is set to TRUE.
   * - Otherwise set to FALSE.
   */
  "TLS EV Capable": "True" | "False";
  /**
   * A boolean value configured by the CCADB:
   * - Set to TRUE for a root certificate record if 'Trust Bits For All Root Stores' contains Code Signing.
   * - Set to TRUE for an intermediate certificate record if 'Derived Trust Bits' contains Code Signing.
   * - Otherwise set to FALSE.
   */
  "Code Signing Capable": "True" | "False";
  /**
   * A boolean value configured by the CCADB:
   * - Set to TRUE for a root certificate record if 'Trust Bits For All Root Stores' contains Secure Email.
   * - Set to TRUE for an intermediate certificate record if 'Derived Trust Bits' contains Secure Email.
   * - Otherwise set to FALSE.
   */
  "S/MIME Capable": "True" | "False";
  /**
   * A text value provided by the CA Owner representing the physical address of their organization.
   */
  Country: string;
};

export type RootCARecord = BaseCARecord & {
  "Certificate Record Type": "Root Certificate";

  /**
   * Certificate status in Apple
   * For root certificates, this status indicates the certificates inclusion status with this program.
   */
  "Apple Status": "Blocked" | "Included" | "Not Included" | "Removed";

  /**
   * Certificate status in Google Chrome
   * For root certificates, this status indicates the certificates inclusion status with this program.
   */
  "Chrome Status": "Blocked" | "Included" | "Not Included" | "Removed";

  /**
   * Certificate status in Microsoft
   * For root certificates, this status indicates the certificates inclusion status with this program.
   */
  "Microsoft Status": "Blocked" | "Included" | "Not Included" | "Removed";

  /**
   * Certificate status in Mozilla
   * For root certificates, this status indicates the certificates inclusion status with this program.
   */
  "Mozilla Status": "Blocked" | "Included" | "Not Included" | "Removed";

  /**
   * When related fields are updated on a intermediate certificate record, a trigger method launches an asynchronous process that updates this field (if needed) for every certificate within that record's CCADB hierarchy.
   *
   * - Set to empty when the certificate is expired or revoked.
   * - Directly map to EKU values when the certificate's EKU is present and not empty.
   * - If the EKU is empty or not present, then set "Derived Trust Bits" to the union of the trust-bits/EKUs that are on the parent root certificate for each root store that it is included in.
   * - Check for same Subject+SPKI root certificates, and if found, update the union to add the trust-bits/EKUs that are on the parent root certificate for each root store that it is included in (if not already in the union).
   * - If this certificate has an intermediate certificate as its parent in the CCADB, then:
   *   - Create "List2" that consists of the parent certificate’s "Derived Trust Bits" unioned with the "Derived Trust Bits" of all of the parent certificate’s unexpired unrevoked same Subject+SPKI certificates.
   *   - Remove anything from this certificate's "Derived Trust Bits" that is not in "List2".
   *
   * Example: "Server Authentication;Client Authentication;Encrypting File System"
   */
  "Trust Bits for Root Cert": string;

  /**
   * This field is updated once daily by a batch program in the CCADB. It includes the union of all EV OIDs, as specified by Root Store Operators
   *
   * Example: "1.3.6.1.4.1.14777.6.1.1; 1.3.6.1.4.1.14777.6.1.2; 2.23.140.1.1" */
  "EV OIDs for Root Cert": string;
};

export type IntermediateCARecord = BaseCARecord & {
  "Certificate Record Type": "Intermediate Certificate";

  /**
   * Certificate status in Apple
   * For intermediate certificates, this will be Not Trusted if it is revoked, expired, or otherwise does not meet program-specific criteria. Otherwise set to Trusted.
   */
  "Apple Status": "Trusted" | "Not Trusted";

  /**
   * Certificate status in Google Chrome
   * For intermediate certificates, this will be Not Trusted if it is revoked, expired, or otherwise does not meet program-specific criteria. Otherwise set to Trusted.
   */
  "Chrome Status": "Trusted" | "Not Trusted";

  /**
   * Certificate status in Microsoft
   * For intermediate certificates, this will be Not Trusted if it is revoked, expired, or otherwise does not meet program-specific criteria. Otherwise set to Trusted.
   */
  "Microsoft Status": "Trusted" | "Not Trusted";

  /**
   * Certificate status in Mozilla
   * For intermediate certificates, this will be Not Trusted if it is revoked, expired, or otherwise does not meet program-specific criteria. Otherwise set to Trusted.
   */
  "Mozilla Status": "Trusted" | "Not Trusted";

  /**
   * Only applicable to the Intermediate Certificate record type, the revocation status for this certificate as configured by the CA Owner.
   */
  "Revocation Status": "Not Revoked" | "Parent Cert Revoked" | "Revoked";

  /**
   * A SHA-256 hash of the parent certificate, as generated by the CCADB when the parent certificate PEM was added. */
  "Parent SHA-256 Fingerprint": string;

  /**
   * When related fields are updated on a intermediate certificate record, a trigger method launches an asynchronous process that updates this field (if needed) for every certificate within that record's CCADB hierarchy.
   * - Set to empty when the certificate is expired or revoked.
   * - Directly map to EKU values when the certificate's EKU is present and not empty.
   * - If the EKU is empty or not present, then set "Derived Trust Bits" to the union of the trust-bits/EKUs that are on the parent root certificate for each root store that it is included in.
   * - Check for same Subject+SPKI root certificates, and if found, update the union to add the trust-bits/EKUs that are on the parent root certificate for each root store that it is included in (if not already in the union).
   * - If this certificate has an intermediate certificate as its parent in the CCADB, then:
   *   - Create "List2" that consists of the parent certificate’s "Derived Trust Bits" unioned with the "Derived Trust Bits" of all of the parent certificate’s unexpired unrevoked same Subject+SPKI certificates.
   *   - Remove anything from this certificate's "Derived Trust Bits" that is not in "List2".
   *
   * Example: "Client Authentication;Secure Email;Server Authentication"
   */
  "Derived Trust Bits": string;

  /**
   * A boolean value configured by the CA Owner for intermediate certificates:
   * - Set to TRUE if this certificate has the same Certificate Policy (CP) information as the issuing certificate (or a subset). Otherwise set to FALSE.
   */
  "CP Same as Parent": "true" | "false";

  /**
   * A boolean value configured by the CA Owner for intermediate certificates:
   * - Set to TRUE if this certificate has the same Certification Practice Statement (CPS) information as the issuing certificate (or a subset). Otherwise set to FALSE
   */
  "CPS Same as Parent": "true" | "false";

  /**
   * A boolean value configured by the CA Owner for intermediate certificates:
   * - Set to TRUE if this certificate has the same combined CP/CPS information as the issuing certificate (or a subset). Otherwise set to FALSE.
   */
  "CP/CPS Same as Parent": "true" | "false";

  /**
   * A boolean value configured by the CA Owner for intermediate certificates.
   * - Set to TRUE if this certificate has the same combined Markdown or AsciiDoc CP/CPS information as the issuing certificate (or a subset). Otherwise set to FALSE.
   */
  "MD/AsciiDoc CP/CPS Same as Parent": "true" | "false";
};

export type CARecord = RootCARecord | IntermediateCARecord;

export type PEMRecord = {
  "SHA-256 Fingerprint": string;
  "X.509 Certificate (PEM)": string;
};
